version: '3.4'
services:
  nginx:
    environment: 
      - NGINX_PORT=8080
      - NGINX_SSL_PORT=8443
    host: 0.0.0.0
    ports:
      - "${NGINX_PORT:-80}:80"
      - "${NGINX_SSL_PORT:-443}:443"
  api:
    expose:
      - "8000"
  frontend:
    restart: "no"
